#!/usr/bin/env node

/**
 * Generates src/version.ts from package.json version
 * Run before build to ensure version is always in sync
 */

import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = join(__dirname, '..')

const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf-8'))
const version = pkg.version

const content = `// Auto-generated by scripts/generate-version.js - do not edit manually
export const VERSION = '${version}'
`

writeFileSync(join(rootDir, 'src', 'version.ts'), content)
console.log(`Generated src/version.ts with version ${version}`)
